### PR TITLE
Get current year copyright footer

### PR DESCRIPTION
**Pull request by EndenDragon**
Have python to import the current year and echo out for the copyright footer. Courtesy of AppleDash. 👍 

(sorry for all this pull requests, i apparently suck at forking 😎 )

### CODE REVIEW

**Comment by uecasm** [comment]
It's not legal to have an automatically updating copyright year.  It can only be updated when some reasonably significant change is performed to the site content in that year.

And it doesn't have to be right up to date anyway; we're covered for at least 25 years. :grinning:

**Comment by AppleDash** [comment]
See also: 
http://law.stackexchange.com/questions/7630/is-it-legal-in-the-us-to-update-my-website-copyright-automatically

**Comment by AppleDash** [comment]
I'm pretty sure there's no legality or illegality here. I don't know 
where you read that.

**Comment by uecasm** [comment]
I guess it's kind of a moot point, since the line isn't a legal declaration anyway as "BronyTV" isn't a real entity.

**Pull request merged**
